### ISSUE TITLE
配置qbot出错，望大佬帮忙看看

### ISSUE THREAD

**Issue by azi666** [captain686/Youth-Learning#15]
[2022-03-17 15:27:28] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:8080/ws/ 
[2022-03-17 15:27:28] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused

**Comment by captain686** [comment]
运行python listen.py

**Comment by captain686** [comment]
> [202-17 15:27:28] [INFO]: 开始尝试连接到另一个 WebSocket 通用服务器: ws//127.0.1:8080/ws/ [022-03-17 15:27:28] [WARNING]: 连接到WebSocket Universal Server ws://127.0.0.1:8080/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection denied

运行 dxx目录下的listen.py后再启动qbot，建议采用Linux环境下使用docker运行

**Comment by captain686** [comment]
> [2022-03-17 15:27:28] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:8080/ws/ [2022-03-17 15:27:28] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused

运行dxx目录下的listen.dxx，然后从目录启动qbot，建议采用环境下使用docker
