### ISSUE TITLE
不同省份适配问题

### ISSUE THREAD

**Issue by cangshanwuyv** [captain686/Youth-Learning#16]
你好，黑龙江共青团平台上的青年大学习抓取不到openid，大佬可不可以帮忙适配一下。

**Comment by captain686** [comment]
> 黑龙江共青团平台上的

提供一下你们所用公众号名称或所用平台网址，有时间我看一下

**Comment by cangshanwuyv** [comment]
公众号：黑龙江共青团
里面的学习频道进去即可
网址：http://tsw.ithyxy.com/mall/Enty.html&amp;response_type=code&amp;scope=snsapi_base&amp;state=123
直接用微信应该是打不开
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "captain686/Youth-Learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月21日(星期一) 中午1:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [captain686/Youth-Learning] 不同省份适配问题 (Issue #16)





  
黑龙江共青团平台上的
  
提供一下你们所用公众号名称或所用平台网址，有时间我看一下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by captain686** [comment]
> 公众号：黑龙江共青团 里面的学习频道进去即可 网址：http://tsw.ithyxy.com/mall/Enty.html&amp;response_type=code&amp;scope=snsapi_base&amp;state=123 直接用微信应该是打不开 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "captain686/Youth-Learning" ***@***.***&gt;; 发送时间:&nbsp;2022年3月21日(星期一) 中午1:25 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [captain686/Youth-Learning] 不同省份适配问题 (Issue #16) 黑龙江共青团平台上的 提供一下你们所用公众号名称或所用平台网址，有时间我看一下 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

黑龙江使用的公众号的完成观看任务的后台请求对应的数据包为
GET /h5/learn/enter?id=150 HTTP/1.1
Host: tsw.ithyxy.com
Connection: close
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 NetType/WIFI MicroMessenger/7.0.20.1781(0x6700143B) WindowsWechat(0x63060012)
Cookie: 你的Cookie
Referer: http://tsw.ithyxy.com/mall/Loop?pid=14&name=%E7%AC%AC%E5%8D%81%E4%BA%8C%E5%AD%A3%C2%B7%E4%B8%80%E8%B5%B7%E5%AD%A6%E5%85%9A%E5%8F%B2
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
与本项目并不兼容，需要重写全部代码

**Comment by captain686** [comment]
> 公众号：黑龙江共青团 里面的学习频道进去即可 网址：http://tsw.ithyxy.com/mall/Enty.html&amp;response_type=code&amp;scope=snsapi_base&amp;state=123 直接用微信应该是打不开 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "captain686/Youth-Learning" ***@***.***&gt;; 发送时间:&nbsp;2022年3月21日(星期一) 中午1:25 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [captain686/Youth-Learning] 不同省份适配问题 (Issue #16) 黑龙江共青团平台上的 提供一下你们所用公众号名称或所用平台网址，有时间我看一下 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

由于手中暂无该省账号无法详细调试

**Comment by cangshanwuyv** [comment]
抓取的post如图，关键信息我害怕被找到个人身份打了码，您看根据这个能试试吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "captain686/Youth-Learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月21日(星期一) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [captain686/Youth-Learning] 不同省份适配问题 (Issue #16)





  
公众号：黑龙江共青团 里面的学习频道进去即可 网址：http://tsw.ithyxy.com/mall/Enty.html&amp;amp;response_type=code&amp;amp;scope=snsapi_base&amp;amp;state=123 直接用微信应该是打不开 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "captain686/Youth-Learning" @.&gt;; 发送时间:&nbsp;2022年3月21日(星期一) 中午1:25 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [captain686/Youth-Learning] 不同省份适配问题 (Issue #16) 黑龙江共青团平台上的 提供一下你们所用公众号名称或所用平台网址，有时间我看一下 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
由于手中暂无该省账号无法详细调试
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by captain686** [comment]
> 

由于公众号使用cookie验证身份，无法保证持久性登录，虽已找到登录接口但是暂时未找到关键参数的加密方式，无法逆向关键参数，所以现在暂时无法解决该问题，抱歉

**Comment by cangshanwuyv** [comment]
收到，还是要感谢你的耐心帮助。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "captain686/Youth-Learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月21日(星期一) 下午5:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [captain686/Youth-Learning] 不同省份适配问题 (Issue #16)





   
由于公众号使用cookie验证身份，无法保证持久性登录，虽已找到登录接口但是暂时未找到关键参数的加密方式，无法逆向关键参数，所以现在暂时无法解决该问题，抱歉
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
