### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by lxh514618** [captain686/Youth-Learning#18]
执行docker exec -it $(docker ps|grep qndxx|awk '{print $1}') /bin/bash报错，提示docker exec需要两个参数

**Comment by captain686** [comment]
> 执行docker exec -it $(docker ps|grep qndxx|awk '{print $1}') /bin/bash报错，提示docker exec需要两个参数

运行docker ps 查看正在运行的容器中有没有qndxx的容器，如果有运行docker exec -it id /bin/bash
将此命令中的id换成docker ps里面的CONTAINER ID值

**Comment by lxh514618** [comment]
没有qndxx容器

**Comment by lxh514618** [comment]
找不到openid

**Comment by lxh514618** [comment]
楼主能帮忙看下嘛，公众号青春黔言

**Comment by captain686** [comment]
> 楼主能帮忙看下嘛，公众号青春黔言

有时间我看一下，可能不兼容

**Comment by lxh514618** [comment]
好的感谢
