### ISSUE TITLE
如何配置在本地win10主机中运行

### ISSUE THREAD

**Issue by MicalShow** [captain686/Youth-Learning#21]
本地有一台Win10 NAS处于常年开机状态，我想要把脚本挂在这台主机上，请问如何修改能让脚本兼容Win10操作系统？

**Comment by captain686** [comment]
> 本地有一个项目赢了10年主动修改的状态，我想把NAS挂在这台上，请问如何实现连续赢10个？

本地版本在[localVersion](https://github.com/captain686/Youth-Learning/tree/localVersion)分支，只需要本地配置相应环境即可

**Comment by MicalShow** [comment]
明白了，谢谢
