### ISSUE TITLE
请问是否支持aarch64设备运行

### ISSUE THREAD

**Issue by cclucky1** [captain686/Youth-Learning#22]
感谢大佬的付出
我手头有刷了armbian的N1盒子 能正常跑docker 请问是否适配了arm架构的设备呢

**Comment by captain686** [comment]
> 感谢大佬的付出 我手头有刷了armbian的N1盒子 能正常跑docker 请问是否适配了arm架构的设备呢

需要重构arm版本docker镜像，下个版本打算直接使用github运行，你可以等下个版本更新，有时间后续我做一下arm的docker镜像

**Comment by cclucky1** [comment]
万分感谢 非常期待！

**Comment by cclucky1** [comment]
你好，我在腾讯云的服务器里执行最后一步出现了错误，能否指点一下是哪个步骤出现了问题，百度没有找到合适的解决方法 换apt源，更改host均尝试过

```bashba s
ERROR: Service 'qndxx' failed to build: The command '/bin/sh -c apt-get update --fix-missing     &&apt-get install -y cron     && fc-cache /usr/share/fonts/chinese/     && service cron start' returned a non-zero code: 1
```

**Comment by captain686** [comment]
> 你好，我在腾讯云的服务器里执行最后一步出现了错误，能否指点一下是哪个步骤出现了问题，百度没有找到合适的解决方法 换apt源，更改host均尝试过
> 
> ```
> ERROR: Service 'qndxx' failed to build: The command '/bin/sh -c apt-get update --fix-missing     &&apt-get install -y cron     && fc-cache /usr/share/fonts/chinese/     && service cron start' returned a non-zero code: 1
> ```

docker version看一下你的docker版本，，我用的是20.10.12，这个问题我之前也遇到过，稍候我看看是因为什么问题导致的

**Comment by captain686** [comment]
> 你好，我在腾讯云的服务器里执行最后一步出现了错误，能否指点一下是哪个步骤出现了问题，百度没有找到合适的解决方法 换apt源，更改host均尝试过
> 
> ```
> ERROR: Service 'qndxx' failed to build: The command '/bin/sh -c apt-get update --fix-missing     &&apt-get install -y cron     && fc-cache /usr/share/fonts/chinese/     && service cron start' returned a non-zero code: 1
> ```

你可以试一下在 https://github.com/captain686/Youth-Learning/blob/master/Dockerfile#L15
这个位置添加一行RUN apt-get clean
然后删除旧的docker镜像重新运行docker-compose up

**Comment by cclucky1** [comment]
刚刚尝试了一下 几乎是同样的问题 在第15行加入了RUN apt-get clean
返回值由1变为了100
ERROR: Service 'qndxx' failed to build: The command '/bin/sh -c apt-get update --fix-missing     &&apt-get install -y cron     && fc-cache /usr/share/fonts/chinese/     && service cron start' returned a non-zero code: 100

**Comment by captain686** [comment]
> 刚刚尝试了一下 几乎是同样的问题 在第15行加入了RUN apt-get clean 返回值由1变为了100 ERROR: Service 'qndxx' failed to build: The command '/bin/sh -c apt-get update --fix-missing &&apt-get install -y cron && fc-cache /usr/share/fonts/chinese/ && service cron start' returned a non-zero code: 100

明天我修复一下

**Comment by cclucky1** [comment]
Docker Version Info
[root@VM-4-4-centos Youth-Learning]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Wed Mar  2 15:25:43 2022
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Wed Mar  2 15:25:43 2022
 OS/Arch:         linux/amd64
 Experimental:    false

**Comment by cclucky1** [comment]
好的 万分感谢 早点休息🌙

**Comment by captain686** [comment]
> Docker Version Info [root@VM-4-4-centos Youth-Learning]# docker version Client: Version: 1.13.1 API version: 1.26 Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64 Go version: go1.10.3 Git commit: 7d71120/1.13.1 Built: Wed Mar 2 15:25:43 2022 OS/Arch: linux/amd64
> 
> Server: Version: 1.13.1 API version: 1.26 (minimum version 1.12) Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64 Go version: go1.10.3 Git commit: 7d71120/1.13.1 Built: Wed Mar 2 15:25:43 2022 OS/Arch: linux/amd64 Experimental: false

你重新clone一下项目删除之前的环境重新运行一下试试，如果不行，尝试把docker升级到20版本试试，我本地用centos尝试可以运行docker版本为Docker version 20.10.5

**Comment by cclucky1** [comment]
换用了Docker版本 所有服务都正常跑起来了 测试可用 感谢 望后续可以提供只有该界面截图的模版
<img width="185" alt="image" src="https://user-images.githubusercontent.com/53963267/167329916-72503c9b-f2de-4627-8ea2-892189d5e47d.png">

**Comment by captain686** [comment]
> 换用了Docker版本 所有服务都正常跑起来了 测试可用 感谢 望后续可以提供只有该界面截图的模版 <img alt="image" width="185" src="https://user-images.githubusercontent.com/53963267/167329916-72503c9b-f2de-4627-8ea2-892189d5e47d.png">

这个你可以修改一下代码，把https://github.com/captain686/Youth-Learning/blob/master/dxx/pic.py#L38
这里的
```python
        self.join(new_1, new_2, new_3, flag='horizontal')
        os.remove(new_1)
        os.remove(new_2)
        self.addInfo(tffPath,new_3,endPath,info)
        os.remove(new_3)
```
改为
```python
        os.remove(new_2)
        self.addInfo(tffPath,new_1,endPath,info)
        os.remove(new_1)
```
然后重新配置一下项目
