### ISSUE TITLE
无法启动docker，log提示没有start.sh这个文件

### ISSUE THREAD

**Issue by Lixuhuilll** [captain686/Youth-Learning#23]

**Comment by Lixuhuilll** [comment]
> > 我注释掉Dockerfiles最后一行的cmd指令后进入docker容器内部查看，发现dxx文件夹没有文件 ![image](https://user-images.githubusercontent.com/88485037/169105351-206c5b47-8dd9-4999-8fc2-7fd84c222291.png)
> 
> 请提供一下所用分支
我使用的是arm64分支

**Comment by Lixuhuilll** [comment]
> > 我注释掉Dockerfiles最后一行的cmd指令后进入docker容器内部查看，发现dxx文件夹没有文件 ![image](https://user-images.githubusercontent.com/88485037/169105351-206c5b47-8dd9-4999-8fc2-7fd84c222291.png)
> 
> 请提供一下所用分支

clone下来的文件夹里dxx文件夹文件齐全，但是使用dockerfiles创建好docker容器后，容器内部的dxx文件夹只有Dxxlog和img文件夹

**Comment by captain686** [comment]
> > > 我注释掉Dockerfiles最后一行的cmd指令后进入docker容器内部查看，发现dxx文件夹没有文件 ![image](https://user-images.githubusercontent.com/88485037/169105351-206c5b47-8dd9-4999-8fc2-7fd84c222291.png)
> > 
> > 
> > 请提供一下所用分支
> 
> clone下来的文件夹里dxx文件夹文件齐全，但是使用dockerfiles创建好docker容器后，容器内部的dxx文件夹只有Dxxlog和img文件夹

好的，稍等我看一下

**Comment by Lixuhuilll** [comment]
问题依旧，我已经用sudo docker rmi 删除了原有镜像然后重新构建，我怀疑是不是我的docekr comose有点问题，我用的一键安装脚本安装的docker
![image](https://user-images.githubusercontent.com/88485037/169115991-a7a4f307-8802-4044-a236-380d0b6d3ecd.png)

**Comment by captain686** [comment]
> 问题依旧，我已经用sudo docker rmi 删除了原有镜像然后重新构建，我怀疑是不是我的docekr comose有点问题，我用的一键安装脚本安装的docker

![image](https://user-images.githubusercontent.com/53248484/169117064-4242cfdd-9c00-4369-a7ed-e2df1cfd4b63.png)
这是我的docker版本，目前我也不清楚具体问题是什么，你可以尝试使用docker cp命令讲文件手动复制进docker中

**Comment by Lixuhuilll** [comment]
可行，之前用copy命令的时候0.0s就执行完成，现在用了1.7s
![image](https://user-images.githubusercontent.com/88485037/169118921-5dcb0910-ad77-4159-8a43-862b0cbf6a14.png)

**Comment by Lixuhuilll** [comment]
我放弃用docker了，这个能直接在本机环境运行吗
![image](https://user-images.githubusercontent.com/88485037/169119364-c773e45f-16a0-4738-b035-d9ab48591dc1.png)

**Comment by Lixuhuilll** [comment]
明明这构建的过程看起来没问题
![image](https://user-images.githubusercontent.com/88485037/169119707-3a2d9d7d-e54c-4e60-adf0-0e2ce7f877c3.png)

**Comment by captain686** [comment]
> 我放弃用docker了，这个能直接在本机环境运行吗 ![image](https://user-images.githubusercontent.com/88485037/169119364-c773e45f-16a0-4738-b035-d9ab48591dc1.png)

可以，但是arm版本很麻烦，因为需要配置selenium环境，你可以等一等，我在做github版，最近几天应该就能完成

**Comment by captain686** [comment]
> 我放弃用docker了，这个能直接在本机环境运行吗 ![image](https://user-images.githubusercontent.com/88485037/169119364-c773e45f-16a0-4738-b035-d9ab48591dc1.png)

方便的话可以加一下[tg群](https://t.me/+0uBS1nTmvSMwNzVl)我帮你看一下是怎么回事

**Comment by Lixuhuilll** [comment]
> > 我放弃用docker了，这个能直接在本机环境运行吗 ![image](https://user-images.githubusercontent.com/88485037/169119364-c773e45f-16a0-4738-b035-d9ab48591dc1.png)
> 
> 方便的话可以加一下[tg群](https://t.me/+0uBS1nTmvSMwNzVl)我帮你看一下是怎么回事

可以，我明天进群吧，今天得睡了，明天有课

**Comment by Lixuhuilll** [comment]
我把dockerfiles改成这样之后，temp文件夹里有dxx的文件，但是dxx文件夹还是空的
![image](https://user-images.githubusercontent.com/88485037/169189991-b12954d0-5bc8-466d-9c44-4e2e919de684.png)

**Comment by Lixuhuilll** [comment]
能跑了，不知道为什么，dxx文件夹会被清空，文件复制到temp文件夹就可以完美运行
![image](https://user-images.githubusercontent.com/88485037/169195456-513e6ef9-2f2c-4812-b213-a3e50f6cbff5.png)
